FROM python:3.12.2-slim-bullseye

WORKDIR /usr/src/djangobnb_backend


# the folllowing line: PYTHONDONTWRITEBYTECODE 1, is to prevent python from writing pyc files to the disk
ENV PYTHONDONTWRITEBYTECODE 1
# the folloiwng line: PYTHONUNBUFFERED 1, is to prevent python from buffering stdout and stderr
ENV PYTHONUNBUFFERED 1
RUN apt-get update && apt-get install -y netcat
# Install system dependencies
RUN pip install --upgrade pip
COPY ./requirements.txt .
RUN pip install -r requirements.txt

COPY ./entrypoint.sh .
# WE PUT THE FOLLOWING LINE TO REMOVE THE CARRIAGE RETURN CHARACTERS FROM THE ENTRYPOINT.SH FILE BECAUSE IT WAS CREATED IN WINDOWS BY CARRIAGE RETURN CHARACTERS MEANS THE SIGNS OF THE END OF THE LINE LIKE THE NEW LINE CHARACTER \n
RUN sed -i 's/\r$//g' /usr/src/djangobnb_backend/entrypoint.sh
RUN chmod +x /usr/src/djangobnb_backend/entrypoint.sh

COPY . .

ENTRYPOINT [ "/usr/src/djangobnb_backend/entrypoint.sh" ]

